# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generated_code.api_pb2 as api__pb2


class FeaturePrinterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePythonCode = channel.unary_unary(
                '/featureprinter.FeaturePrinter/GeneratePythonCode',
                request_serializer=api__pb2.FeatureRequest.SerializeToString,
                response_deserializer=api__pb2.PythonCodeResponse.FromString,
                )


class FeaturePrinterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeneratePythonCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeaturePrinterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePythonCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePythonCode,
                    request_deserializer=api__pb2.FeatureRequest.FromString,
                    response_serializer=api__pb2.PythonCodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'featureprinter.FeaturePrinter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FeaturePrinter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePythonCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/featureprinter.FeaturePrinter/GeneratePythonCode',
            api__pb2.FeatureRequest.SerializeToString,
            api__pb2.PythonCodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
