# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x0e\x66\x65\x61tureprinter\"1\n\x0e\x46\x65\x61tureRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\t\x12\r\n\x05types\x18\x02 \x03(\t\")\n\x12PythonCodeResponse\x12\x13\n\x0bpython_code\x18\x01 \x01(\t2j\n\x0e\x46\x65\x61turePrinter\x12X\n\x12GeneratePythonCode\x12\x1e.featureprinter.FeatureRequest\x1a\".featureprinter.PythonCodeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FEATUREREQUEST']._serialized_start=29
  _globals['_FEATUREREQUEST']._serialized_end=78
  _globals['_PYTHONCODERESPONSE']._serialized_start=80
  _globals['_PYTHONCODERESPONSE']._serialized_end=121
  _globals['_FEATUREPRINTER']._serialized_start=123
  _globals['_FEATUREPRINTER']._serialized_end=229
# @@protoc_insertion_point(module_scope)
